/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */

import {
  USER_SIGN_UP,
  USER_SIGN_UP_ERROR,
  USER_LOGIN,
  USER_LOGIN_ERROR
} from './authentication/const'

import {
  ADD_TO_FAVOURITES,
  REMOVE_FROM_FAVOURITES,
  GET_FAVOURITES_ESTATES
} from './favourites/const'

import {
  ADD_ESTATE_INFORMATION,
  ADD_ESTATE_INFORMATION_ERROR,
  GET_ESTATES,
  GET_ESTATES_ERROR,
  GET_ESTATE_BY_ID,
  GET_ESTATE_BY_ID_ERROR
} from './estate/const'

import {
  GET_USER_BY_ID,
  GET_USER_BY_ID_ERROR,
  GET_USER
} from './user/const'

export {
  USER_SIGN_UP,
  USER_SIGN_UP_ERROR,
  USER_LOGIN,
  USER_LOGIN_ERROR,
  ADD_ESTATE_INFORMATION,
  ADD_ESTATE_INFORMATION_ERROR,
  GET_ESTATES,
  GET_ESTATES_ERROR,
  GET_ESTATE_BY_ID,
  GET_ESTATE_BY_ID_ERROR,
  ADD_TO_FAVOURITES,
  REMOVE_FROM_FAVOURITES,
  GET_USER_BY_ID,
  GET_USER_BY_ID_ERROR,
  GET_USER,
  GET_FAVOURITES_ESTATES
}
