/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */

import {
  USER_SIGN_UP,
  USER_SIGN_UP_ERROR,
  USER_LOGIN,
  USER_LOGIN_ERROR
} from './authentication/const'

import {
  ADD_TO_FAVOURITES,
  REMOVE_FROM_FAVOURITES,
  GET_FAVOURITES_ESTATES
} from './favourites/const'

import {
  ADD_ESTATE_INFORMATION,
  ADD_ESTATE_INFORMATION_ERROR,
  GET_ESTATES,
  GET_ESTATES_ERROR,
  GET_ESTATE_BY_ID,
  GET_ESTATE_BY_ID_ERROR
} from './estate/const'

import {
  GET_USER_BY_ID,
  GET_USER_BY_ID_ERROR,
  GET_USER
} from './user/const'

import {
  ADMIN_ADD_CATEGORY,
  ADMIN_GET_CATEGORIES,
  ADMIN_GET_CATEGORY,
  ADMIN_DELETE_CATEGORY,
  ADMIN_UPDATE_CATEGORY,
  ADMIN_GET_REFINEMENTS,
  ADMIN_GET_REFINEMENT,
  ADMIN_DELETE_REFINEMENT,
  ADMIN_UPDATE_REFINEMENT,
  GET_ONLINE_CATEGORIES,
  GET_REFINEMENTS_BY_TYPE
} from './category/const'

import {
  UPDATE_SEARCH_INDEX,
  UPDATE_SEARCH_INDEX_ERROR,
  SET_DEFAULT_SEARCH_INDEX
} from './search/const'

export {
  USER_SIGN_UP,
  USER_SIGN_UP_ERROR,
  USER_LOGIN,
  USER_LOGIN_ERROR,
  ADD_ESTATE_INFORMATION,
  ADD_ESTATE_INFORMATION_ERROR,
  GET_ESTATES,
  GET_ESTATES_ERROR,
  GET_ESTATE_BY_ID,
  GET_ESTATE_BY_ID_ERROR,
  ADD_TO_FAVOURITES,
  REMOVE_FROM_FAVOURITES,
  GET_USER_BY_ID,
  GET_USER_BY_ID_ERROR,
  GET_USER,
  GET_FAVOURITES_ESTATES,
  ADMIN_ADD_CATEGORY,
  ADMIN_GET_CATEGORIES,
  ADMIN_GET_CATEGORY,
  ADMIN_DELETE_CATEGORY,
  ADMIN_UPDATE_CATEGORY,
  ADMIN_GET_REFINEMENTS,
  ADMIN_GET_REFINEMENT,
  ADMIN_DELETE_REFINEMENT,
  ADMIN_UPDATE_REFINEMENT,
  GET_ONLINE_CATEGORIES,
  UPDATE_SEARCH_INDEX,
  UPDATE_SEARCH_INDEX_ERROR,
  SET_DEFAULT_SEARCH_INDEX,
  GET_REFINEMENTS_BY_TYPE
}
