export const ADD_ESTATE_INFORMATION = 'ADD_ESTATE_INFORMATION'
export const ADD_ESTATE_INFORMATION_ERROR = 'ADD_ESTATE_INFORMATION_ERROR'

export const GET_ESTATES = 'GET_ESTATES'
export const GET_ESTATES_ERROR = 'GET_ESTATES_ERROR'

export const GET_ESTATE_BY_ID = 'GET_ESTATE_BY_ID'
export const GET_ESTATE_BY_ID_ERROR = 'GET_ESTATE_BY_ID_ERROR'
