// Settings configured here will be merged into the final config object.
export default {
  'Видин': 'vidin',
  'Благоевград': 'blagoevgrad',
  'Бургас': 'burgas',
  'Добрич': 'dobrich',
  'София - Област': 'sofia',
  'Хасково': 'haskovo',
  'Кюстендил': 'kuistendil',
  'Габрово': 'gabrovo',
  'Кърджали': 'kurdjali',
  'Ловеч': 'lovech',
  'Монтана': 'montana',
  'Пазарджик': 'pazardjik',
  'Перник': 'pernik',
  'Плевен': 'pleven',
  'Пловдив': 'plovdiv',
  'Разград': 'razgrad',
  'Русе': 'ruse',
  'Шумен': 'shumen',
  'Силистра': 'silistra',
  'Сливен': 'sliven',
  'Смолян': 'smolyan',
  'Стара Загора': 'stara_zagora',
  'Търговище': 'turgovishte',
  'Варна': 'varna',
  'Велико Търново': 'veliko_turnovo',
  'Враца': 'vratsa',
  'Ямбол': 'yambol'
};
